{
 "title": "Übersicht",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  aussentemperatur AS \"Außentemperatur\",\n  vorlauftemperatur AS \"Vorlauftemperatur\",\n  ruecklauftemperatur AS \"Rücklauftemperatur\"\nFROM data\nORDER BY time"
    }
   ]
  },
  {
   "title": "Netzfrequenz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  frequency_1 AS \"Frequenz WP\",\n  frequency_2 AS \"Frequenz Haus\"\nFROM data\nORDER BY time"
    }
   ]
  },
  {
   "title": "Netzspannung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  l1_voltage_1 AS \"L1 Spannung WP\",\n  l1_voltage_2 AS \"L1 Spannung Haus\"\nFROM data\nORDER BY time"
    }
   ]
  },
  {
   "title": "Aktuelle Werte",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  aussentemperatur AS \"Außentemperatur\",\n  vorlauftemperatur AS \"Vorlauftemperatur\",\n  ruecklauftemperatur AS \"Rücklauftemperatur\"\nFROM data\nORDER BY time"
    }
   ]
  },
  {
   "title": "Spannungsverteilung",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  l1_voltage_1\nFROM data\nORDER BY time"
    }
   ]
  },
  {
   "title": "Frequenzverteilung",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  frequency_1\nFROM data\nORDER BY time"
    }
   ]
  }
 ]
}